(function(){
  const BOOKS=[{id:'b1',title:'The Silent Garden',price:18.99,description:'A lyrical journey'},{id:'b2',title:'Urban Tides',price:22.50,description:'Modern fable'},{id:'b3',title:'The Paper Lantern',price:14.95,description:'Historical mystery'}];
  let currentRoute='home',selectedProductId=null,cart=[];
  const STORAGE_KEY='pagequill_cart';
  function loadCart(){try{const s=localStorage.getItem(STORAGE_KEY);if(s){cart=JSON.parse(s);cart=cart.map(i=>({...i,quantity:Number(i.quantity),price:Number(i.price)}))}}catch(e){cart=[]}}
  function saveCart(){localStorage.setItem(STORAGE_KEY,JSON.stringify(cart))}
  function addToCart(id,title,price,q=1){const e=cart.find(i=>i.id===id);e?e.quantity+=q:cart.push({id,title,price:Number(price),quantity:q});saveCart();renderView();updateNav()}
  function removeFromCart(id){cart=cart.filter(i=>i.id!==id);saveCart();renderView();updateNav()}
  function updateQty(id,d){const i=cart.find(i=>i.id===id);if(!i)return;const n=i.quantity+d;n<=0?removeFromCart(id):(i.quantity=n,saveCart(),renderView(),updateNav())}
  function getTotal(){return cart.reduce((s,i)=>s+i.price*i.quantity,0)}
  function getCount(){return cart.reduce((c,i)=>c+i.quantity,0)}
  function navigateTo(r,id=null){currentRoute=r;selectedProductId=r==='product'?id:null;window.location.hash=r+(id?'/'+id:'');renderView();updateNav()}
  function initHash(){const h=window.location.hash.slice(1)||'home';const p=h.split('/');let r=p[0];if(!['home','catalog','product','cart','about'].includes(r))r='home';currentRoute=r==='product'&&p[1]?r:r;selectedProductId=r==='product'&&p[1]?p[1]:null;renderView();updateNav()}
  const app=document.getElementById('appView'),nav=document.getElementById('mainNav');
  function renderNav(){nav.innerHTML=[{id:'home',label:'Home'},{id:'catalog',label:'Books'},{id:'cart',label:`Cart (${getCount()})`},{id:'about',label:'About'}].map(r=>`<button class="nav-btn" data-route="${r.id}">${r.label}</button>`).join('');nav.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>navigateTo(b.dataset.route)))}
  function updateNav(){document.querySelectorAll('.nav-btn').forEach(b=>{b.classList.toggle('active',b.dataset.route===currentRoute);if(b.dataset.route==='cart')b.textContent=`Cart (${getCount()})`})}
  function renderView(){
    const cartBtn=nav.querySelector('[data-route="cart"]');if(cartBtn)cartBtn.textContent=`Cart (${getCount()})`;
    if(currentRoute==='home')app.innerHTML=`<div class="hero"><h2>📚 Page & Quill</h2><p style="font-size:1.3rem;margin-top:1rem">A quiet corner for book lovers.<br>Offline, always.</p><div style="display:flex;gap:1rem;justify-content:center;margin-top:2rem"><button class="btn btn-primary" data-nav="catalog">Browse books</button><button class="btn btn-outline" data-nav="cart">View cart</button></div></div>`;
    else if(currentRoute==='catalog'){app.innerHTML=`<section><h2 style="font-size:2rem">Our shelves</h2><div class="grid-catalog">${BOOKS.map(b=>`<div class="book-card"><div class="book-img">📖 ${b.title}</div><div class="book-title">${b.title}</div><div class="book-price">$${b.price.toFixed(2)}</div><div class="card-actions"><button class="btn btn-outline view-detail" data-id="${b.id}">View</button><button class="btn btn-primary add-to-cart" data-id="${b.id}" data-title="${b.title}" data-price="${b.price}">Add</button></div></div>`).join('')}</div></section>`;app.querySelectorAll('.view-detail').forEach(b=>b.addEventListener('click',()=>navigateTo('product',b.dataset.id)));app.querySelectorAll('.add-to-cart').forEach(b=>b.addEventListener('click',()=>addToCart(b.dataset.id,b.dataset.title,parseFloat(b.dataset.price),1)))}
    else if(currentRoute==='product'){const b=BOOKS.find(b=>b.id===selectedProductId);if(!b)return;app.innerHTML=`<div class="detail-container" style="display:flex;gap:3rem;background:white;border-radius:28px;padding:2.2rem"><div class="detail-img" style="flex:1;background:#cdbcae;border-radius:24px;aspect-ratio:3/4;display:flex;align-items:center;justify-content:center">📘 ${b.title}</div><div style="flex:2"><h2 style="font-size:2.4rem">${b.title}</h2><div style="font-size:2rem;color:#1e5555;margin:1rem 0">$${b.price.toFixed(2)}</div><p style="margin:2rem 0">${b.description}</p><button class="btn btn-primary" id="addDetail">Add to cart</button></div></div>`;document.getElementById('addDetail').addEventListener('click',()=>addToCart(b.id,b.title,b.price,1))}
    else if(currentRoute==='cart'){if(cart.length===0)app.innerHTML=`<div style="padding:3rem;text-align:center;background:#f3efeb;border-radius:32px"><h2>🛒 Cart empty</h2><button class="btn btn-primary" data-nav="catalog">Explore</button></div>`;else{app.innerHTML=`<section><h2 style="font-size:2rem">Your cart</h2>${cart.map(i=>`<div class="cart-item"><div style="flex:2"><div style="font-weight:700">${i.title}</div><div>$${i.price.toFixed(2)}</div></div><div style="display:flex;gap:0.5rem;align-items:center"><button class="qty-btn dec" data-id="${i.id}">−</button><span>${i.quantity}</span><button class="qty-btn inc" data-id="${i.id}">+</button></div><div style="font-weight:600">$${(i.price*i.quantity).toFixed(2)}</div><button class="btn btn-danger remove" data-id="${i.id}">Remove</button></div>`).join('')}<div class="cart-total">Total: $${getTotal().toFixed(2)}</div><button class="btn btn-primary" id="continue">Continue</button></section>`;app.querySelectorAll('.dec').forEach(b=>b.addEventListener('click',()=>updateQty(b.dataset.id,-1)));app.querySelectorAll('.inc').forEach(b=>b.addEventListener('click',()=>updateQty(b.dataset.id,1)));app.querySelectorAll('.remove').forEach(b=>b.addEventListener('click',()=>removeFromCart(b.dataset.id)));document.getElementById('continue')?.addEventListener('click',()=>navigateTo('catalog'))}}
    else if(currentRoute==='about')app.innerHTML=`<div class="about-card"><h2 style="font-size:2.2rem">📬 Page & Quill</h2><p style="margin:1.5rem 0">📍 221B Paper Street</p><p>📞 +1 (555) 204-BOOK</p><p>✉️ hello@pagequill.offline</p></div>`;
    app.querySelectorAll('[data-nav="catalog"]').forEach(b=>b.addEventListener('click',()=>navigateTo('catalog')));app.querySelectorAll('[data-nav="cart"]').forEach(b=>b.addEventListener('click',()=>navigateTo('cart')))
  }
  loadCart();renderNav();window.addEventListener('hashchange',initHash);if(window.location.hash)initHash();else navigateTo('home');
})();